#pragma once

#ifndef MAXNUMATOMS
#define MAXNUMATOMS 3000000
#endif

#ifndef MAXNUMNEIGHBORS
#define MAXNUMNEIGHBORS 500
#endif

#ifndef MINIMUMIMAGECONVENTIONTYPE_BRANCH
#define MINIMUMIMAGECONVENTIONTYPE_BRANCH
#endif
