#pragma once

#ifndef MAXNUMATOMS
#define MAXNUMATOMS 2048
#endif

#ifndef MAXNUMNEIGHBORS
#define MAXNUMNEIGHBORS 100
#endif

#ifndef BENCHMARK
// #define BENCHMARK
#endif

#ifndef MINIMUMIMAGECONVENTIONTYPE_BRANCH
#define MINIMUMIMAGECONVENTIONTYPE_BRANCH
#endif
